# Generic controller egress replacement:
# preserve DNS access and pin API egress to explicit CIDR allow-list entries.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: helloworld-controller
  namespace: shipshape
spec:
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: coredns
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: node-local-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 10.100.12.34/32
        - ipBlock:
            cidr: 10.100.12.35/32
      ports:
        - protocol: TCP
          port: 443
