# AKS example: authoritative egress replacement preserving DNS + strict API CIDR pinning.
# Replace API CIDRs with your AKS control-plane endpoint CIDR(s).
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: helloworld-controller
  namespace: shipshape
spec:
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: coredns
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: node-local-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 10.240.0.9/32
        - ipBlock:
            cidr: 10.240.0.10/32
      ports:
        - protocol: TCP
          port: 443
